{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "f8141c97-6cb6-4175-ac7e-18b652cc2109",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\HomePC\\anaconda3\\envs\\inv2\\Lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "2025-07-21 14:26:06.267 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-21 14:26:07.253 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\HomePC\\anaconda3\\envs\\inv2\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-07-21 14:26:07.273 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-21 14:26:07.338 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-21 14:26:07.347 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-21 14:26:07.398 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-21 14:26:07.402 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-07-21 14:26:07.407 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import google.generativeai as genai\n",
    "import os\n",
    "from dotenv import load_dotenv\n",
    "from pathlib import Path\n",
    "import mimetypes\n",
    "\n",
    "# Load .env\n",
    "load_dotenv()\n",
    "api_key = os.getenv(\"gemini_api\")\n",
    "\n",
    "genai.configure(api_key=api_key)\n",
    "\n",
    "# Model Configuration\n",
    "MODEL_CONFIG = {\n",
    "    \"temperature\": 0.2,\n",
    "    \"top_p\": 1,\n",
    "    \"top_k\": 32,\n",
    "    \"max_output_tokens\": 4096,\n",
    "}\n",
    "\n",
    "safety_settings = [\n",
    "    {\"category\": \"HARM_CATEGORY_HARASSMENT\", \"threshold\": \"BLOCK_MEDIUM_AND_ABOVE\"},\n",
    "    {\"category\": \"HARM_CATEGORY_HATE_SPEECH\", \"threshold\": \"BLOCK_MEDIUM_AND_ABOVE\"},\n",
    "    {\"category\": \"HARM_CATEGORY_SEXUALLY_EXPLICIT\", \"threshold\": \"BLOCK_MEDIUM_AND_ABOVE\"},\n",
    "    {\"category\": \"HARM_CATEGORY_DANGEROUS_CONTENT\", \"threshold\": \"BLOCK_MEDIUM_AND_ABOVE\"},\n",
    "]\n",
    "\n",
    "model = genai.GenerativeModel(\n",
    "    model_name=\"models/gemini-1.5-flash\",\n",
    "    generation_config=MODEL_CONFIG,\n",
    "    safety_settings=safety_settings\n",
    ")\n",
    "\n",
    "def image_format(file_path):\n",
    "    file = Path(file_path)\n",
    "    if not file.exists():\n",
    "        raise FileNotFoundError(f\"Could not find file: {file}\")\n",
    "    mime_type, _ = mimetypes.guess_type(file)\n",
    "    if mime_type not in [\"image/png\", \"image/jpeg\", \"application/pdf\"]:\n",
    "        raise ValueError(f\"Unsupported file type: {mime_type}\")\n",
    "    return [{\"mime_type\": mime_type, \"data\": file.read_bytes()}]\n",
    "\n",
    "def gemini_output(file_path, system_prompt, user_prompt):\n",
    "    file_info = image_format(file_path)\n",
    "    input_prompt = [system_prompt, file_info[0], user_prompt]\n",
    "    response = model.generate_content(input_prompt)\n",
    "    return response.text\n",
    "\n",
    "# Streamlit App\n",
    "st.title(\"AI-Powered Tax Calculator with Invoice Intelligence\")\n",
    "\n",
    "# Upload invoice\n",
    "invoice_file = st.file_uploader(\"Upload an invoice (PDF/Image)\", type=[\"pdf\", \"png\", \"jpg\", \"jpeg\"])\n",
    "\n",
    "if invoice_file:\n",
    "    temp_path = f\"./temp_{invoice_file.name}\"\n",
    "    with open(temp_path, \"wb\") as f:\n",
    "        f.write(invoice_file.read())\n",
    "\n",
    "    system_prompt = \"\"\"\n",
    "        You are an expert in reading invoices and applying Kenyan tax law.\n",
    "        Your job is to:\n",
    "        - Read the uploaded invoice\n",
    "        - Identify line items like service fees, rent, VAT, country of vendor\n",
    "        - Apply correct Kenyan tax rules:\n",
    "            • 2% Withholding for goods\n",
    "            • 5% Withholding for services like legal/consulting\n",
    "            • 7.5% Withholding on rent\n",
    "            • 16% VAT for vendors not VAT-registered\n",
    "            • 20% for foreign vendors (non-resident)\n",
    "        - Extract key details such as:\n",
    "            • Payment narration/description\n",
    "            • Period covered by the invoice\n",
    "        - Return a JSON with:\n",
    "            • Extracted fields\n",
    "            • Tax breakdown\n",
    "            • Total tax payable\n",
    "            • Net amount to pay vendor\n",
    "            • Reasoning for each tax\n",
    "    \"\"\"\n",
    "    user_prompt = \"\"\"\n",
    "        Extract the relevant data from this invoice and calculate the applicable Kenyan taxes.\n",
    "        Output a JSON like this:\n",
    "        {\n",
    "          \"invoice_total\": ..., \n",
    "          \"taxable_amount\": ..., \n",
    "          \"payment_narration\": ..., \n",
    "          \"payment_period\": ...,\n",
    "          \"tax_breakdown\": {\n",
    "            \"Withholding Tax (5%)\": ..., \n",
    "            \"VAT (16%)\": ..., \n",
    "            ...\n",
    "          }, \n",
    "          \"total_tax\": ..., \n",
    "          \"amount_to_pay_vendor\": ..., \n",
    "          \"reasoning\": {\n",
    "            \"Withholding Tax\": \"...\", \n",
    "            \"VAT\": \"...\"\n",
    "          }\n",
    "        }\n",
    "    \"\"\"\n",
    "\n",
    "    with st.spinner(\"Analyzing invoice and applying tax laws...\"):\n",
    "        gemini_result = gemini_output(temp_path, system_prompt, user_prompt)\n",
    "    \n",
    "    st.subheader(\"Gemini Tax Analysis\")\n",
    "    st.code(gemini_result, language=\"json\")\n",
    "\n",
    "    st.write(\"#### Do you want to edit the values manually?\")\n",
    "    if st.checkbox(\"Yes, override values manually\"):\n",
    "        invoiced_amount = st.number_input(\"Enter Invoiced Taxable Amount\", min_value=0.0, format=\"%.2f\")\n",
    "        total_invoice = st.number_input(\"Enter Total Invoice Amount\", min_value=0.0, format=\"%.2f\")\n",
    "        contract_type = st.radio(\"Gross-Up Option\", [\"No Gross\", \"Gross Up\"])\n",
    "\n",
    "        tax_data = {\n",
    "            \"Withholding Tax\": {\n",
    "                \"2% (Goods)\": 0.02,\n",
    "                \"3%\": 0.03,\n",
    "                \"5% (Services)\": 0.05,\n",
    "                \"12.5%\": 0.125,\n",
    "                \"20% (Foreign)\": 0.20,\n",
    "                \"16% (Non-VAT)\": 0.16,\n",
    "            },\n",
    "            \"Rent Tax\": {\"7.5% (Rent)\": 0.075},\n",
    "        }\n",
    "\n",
    "        selected_taxes = {}\n",
    "        for category, rates in tax_data.items():\n",
    "            for tax_label, rate in rates.items():\n",
    "                if st.checkbox(tax_label, key=tax_label):\n",
    "                    applicable_amount = st.number_input(f\"Applicable cost for {tax_label}\", min_value=0.0, value=invoiced_amount)\n",
    "                    selected_taxes[tax_label] = (rate, applicable_amount)\n",
    "\n",
    "        def calculate_taxes(full_amount, total_invoice, tax_components, vendor_cost=True):\n",
    "            tax_breakdown = {}\n",
    "            total_tax = 0\n",
    "            for tax_name, (rate, applicable_amount) in tax_components.items():\n",
    "                tax_value = applicable_amount * rate\n",
    "                tax_breakdown[tax_name] = round(tax_value, 2)\n",
    "                total_tax += tax_value\n",
    "            if vendor_cost:\n",
    "                amount_to_pay = total_invoice - total_tax\n",
    "            else:\n",
    "                amount_to_pay = full_amount + total_tax\n",
    "            return round(total_tax, 2), round(max(amount_to_pay, 0), 2), tax_breakdown\n",
    "\n",
    "        if st.button(\"Calculate Manually\"):\n",
    "            vendor_cost = contract_type == \"No Gross\"\n",
    "            full_amount = invoiced_amount * (100 / 100.0)\n",
    "            total_tax, amount_to_pay, breakdown = calculate_taxes(full_amount, total_invoice, selected_taxes, vendor_cost)\n",
    "            st.subheader(\"Manual Tax Breakdown\")\n",
    "            for name, amount in breakdown.items():\n",
    "                st.write(f\"**{name}**: {amount:.2f}\")\n",
    "            st.success(f\"Total Tax Payable: {total_tax:.2f}\")\n",
    "            st.success(f\"Amount to Pay Vendor: {amount_to_pay:.2f}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f477265e-1af6-4b87-acd7-d62c528e4b36",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (inv2)",
   "language": "python",
   "name": "inv2"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
